2020-02-28 13:43:04,970 	 [INFO | run_locally.py : line 27] >> Pipeline start
2020-02-28 13:43:04,970 	 [INFO | run_locally.py : line 35] >> Using this configuration file = utils/adhoc_config1.csv
2020-02-28 13:43:04,971 	 [ERROR | run_locally.py : line 39] >> utils/adhoc_config1.csv not found
